### ISSUE TITLE
Callbacks documentation fails on RTD

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/APS_BlueSky_tools#63]
probably some *mock* issue

see: https://aps-bluesky-tools.readthedocs.io/en/latest/source_code/callbacks.html

**Comment by prjemian** [comment]
Also 

* Examples: https://aps-bluesky-tools.readthedocs.io/en/latest/source_code/examples.html
* Plans : https://aps-bluesky-tools.readthedocs.io/en/latest/source_code/plans.html
* sscan record : https://aps-bluesky-tools.readthedocs.io/en/latest/source_code/sscan.html
* swait record : https://aps-bluesky-tools.readthedocs.io/en/latest/source_code/swait.html
* Utilities : https://aps-bluesky-tools.readthedocs.io/en/latest/source_code/utils.html

**Comment by prjemian** [comment]
Ok, the pandas mock got Utilities.  Now for the others.  First error:

```
WARNING: autodoc: failed to import module 'callbacks' from module 'APS_BlueSky_tools'; the following exception was raised:
No module named 'pyRestTable'
WARNING: autodoc: failed to import module 'devices' from module 'APS_BlueSky_tools'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/checkouts/latest/APS_BlueSky_tools/devices.py", line 64, in <module>
    from .synApps_ophyd import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/checkouts/latest/APS_BlueSky_tools/synApps_ophyd/__init__.py", line 26, in <module>
    from .busy import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/checkouts/latest/APS_BlueSky_tools/synApps_ophyd/busy.py", line 15, in <module>
    from ophyd.device import Device, Component
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/ophyd/__init__.py", line 88, in <module>
    from .mca import EpicsMCA, EpicsDXP
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/ophyd/mca.py", line 10, in <module>
    from .areadetector import EpicsSignalWithRBV as SignalWithRBV
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/ophyd/areadetector/__init__.py", line 8, in <module>
    from .base import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/ophyd/areadetector/base.py", line 6, in <module>
    import networkx as nx
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/networkx/generators/__init__.py", line 13, in <module>
    from networkx.generators.geometric import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/networkx/generators/geometric.py", line 25, in <module>
    from scipy.spatial import cKDTree as KDTree
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/scipy/__init__.py", line 71, in <module>
    from numpy import *
TypeError: attribute name must be string, not 'MagicMock'
```

**Comment by prjemian** [comment]
It's hung on this error:

```
WARNING: autodoc: failed to import module 'devices' from module 'APS_BlueSky_tools'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/conda/latest/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/aps-bluesky-tools/checkouts/latest/APS_BlueSky_tools/devices.py", line 666, in <module>
    class TunableEpicsMotor(AxisTunerMixin, EpicsMotor):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases```

**Comment by prjemian** [comment]
The original error is fixed.  The last error is now #67.  Closing here.
